### ISSUE TITLE
Reuse existing cache when rebuilding cache

### ISSUE THREAD

**Issue by danielcompton** [borkdude/clj-kondo#705]
**Is your feature request related to a problem? Please describe.**

In CI and when running a full local lint, we build the whole cache before linting our project

```bash
clj-kondo --lint "$(clojure -Spath)" --cache > /dev/null
git ls-files | grep -E '.clj[cs]?$' | xargs clj-kondo --lint
```

Rebuilding the whole cache is a relatively heavyweight operation, but gives us the most complete linting results (I think?). It would be nice if we could reuse this cache between CI builds to save build time.

**Describe the solution you'd like**

I'm not sure if this makes sense, but if each cache entry for an immutable file had an identifier in the name or file, that would let clj-kondo know when it could skip rebuilding the cache.

The tricky part then becomes knowing which files can be considered immutable, and which ones can't. My suggestion would be to only cache JARs with a non SNAPSHOT version.

**Describe alternatives you've considered**

* Not building the cache in CI. I think this might mean we miss some lint warnings?
* Rebuilding the cache in CI every time. This is just slow, but nothing bad happens.

**Comment by borkdude** [comment]
If you're using clj-kondo like this on CI you don't really need a cache.

Note that you can merge these two operations:

```
clj-kondo --lint "$(clojure -Spath)" --cache > /dev/null
git ls-files | grep -E '.clj[cs]?$' | xargs clj-kondo --lint
```

into one:

```
clj-kondo --lint "$(clojure -Spath)" --config '{:output {:include-files ["^src"]}}'
```

The config option takes Java regexes which will be matches using `(re-find (re-pattern %) file-name)`.

The `--cache` option defaults to `true` now, so you don't need it anymore, unless you want to disable caching.

This will likely already save you time.

If that's not enough, you can consider linting your libraries separately and save them to a separate cache directory with `--cache-dir` and use a checksum. You can then check if that directory already exists using the checksum and copy it to .clj-kondo/.cache before you lint your own sources.

**Comment by borkdude** [comment]
So to recap, for CircleCI I would do something like this:

``` yaml
      - restore_cache:
          keys:
            - deps-{{ checksum "deps.edn" }}

      - run:
          name: Lint
          command: |
            if [ -d ~/clj-kondo-cache ] then; # contains deps restored from cache
              clj-kondo --lint src
           else
             clj-kondo --lint $(clojure -Spath)
           fi
      - save_cache:
          paths:
            - ~/.m2
            - ~/clj-kondo-cache
          key: v1-dependencies-{{ checksum "deps.edn" }}
```

Note that I've not tested this, take it as pseudo-code.
